import { supabase } from './supabase';

declare global {
  interface Window {
    OneSignalDeferred?: Array<(os: OneSignalSDK) => void | Promise<void>>;
    OneSignal?: OneSignalSDK;
  }
}

interface OneSignalSDK {
  init(opts: {
    appId: string;
    safari_web_id?: string;
    notifyButton?: { enable: boolean };
    allowLocalhostAsSecureOrigin?: boolean;
  }): Promise<void>;
  login(externalId: string): Promise<void>;
  logout(): Promise<void>;
  Notifications: {
    requestPermission(): Promise<boolean>;
    permissionNative: NotificationPermission;
  };
}

function deferred(fn: (os: OneSignalSDK) => void | Promise<void>) {
  window.OneSignalDeferred = window.OneSignalDeferred || [];
  window.OneSignalDeferred.push(fn);
}

export function initOneSignal() {
  deferred(async (os) => {
    await os.init({
      appId: import.meta.env.VITE_ONESIGNAL_APP_ID as string,
      // Generated by completing OneSignal's Web Push setup for this app — required
      // for push to work on Safari/iOS (every browser on iPhone runs Safari's engine).
      safari_web_id: import.meta.env.VITE_ONESIGNAL_SAFARI_WEB_ID as string,
      notifyButton: { enable: false },
      allowLocalhostAsSecureOrigin: import.meta.env.DEV as boolean,
    });
  });
}

export function loginOneSignal(userId: string) {
  deferred(async (os) => {
    await os.login(userId);
  });
}

export function logoutOneSignal() {
  deferred(async (os) => {
    await os.logout();
  });
}

export async function requestPushPermission(): Promise<boolean> {
  // Safari/iOS only shows the native permission popup when requestPermission()
  // runs synchronously inside a trusted user gesture (the click). Going through
  // the OneSignalDeferred queue defers it to a later tick, which silently loses
  // that trust — no popup, no error, just nothing. By the time a user can reach
  // this Settings toggle, initOneSignal() (called at app startup) has almost
  // certainly already finished, so window.OneSignal is the real SDK — call it
  // directly, in-gesture, instead of queuing.
  if (window.OneSignal?.Notifications?.requestPermission) {
    try {
      return await window.OneSignal.Notifications.requestPermission();
    } catch {
      return false;
    }
  }

  // Fallback for the rare case OneSignal hasn't finished loading yet — the
  // popup may not appear on strict browsers here, but this keeps the app usable.
  return new Promise((resolve) => {
    let settled = false;
    const finish = (granted: boolean) => {
      if (settled) return;
      settled = true;
      resolve(granted);
    };
    deferred(async (os) => {
      try {
        const granted = await os.Notifications.requestPermission();
        finish(granted);
      } catch {
        finish(false);
      }
    });
    setTimeout(() => finish(getPushPermission() === 'granted'), 8000);
  });
}

export function getPushPermission(): NotificationPermission {
  return window.Notification?.permission ?? 'default';
}

export async function sendPush(params: {
  to: 'user' | 'staff';
  userId?: string;
  excludeId?: string;
  title: string;
  body: string;
  url?: string;
}): Promise<void> {
  try {
    await supabase.functions.invoke('send-push', { body: params });
  } catch {
    // Push failures are non-critical — never block the primary action
  }
}

export async function sendLcpFamilyPush(params: {
  title: string;
  body: string;
  url?: string;
}): Promise<void> {
  try {
    await supabase.functions.invoke('send-push-lcp', { body: params });
  } catch {
    // Push failures are non-critical — never block the primary action
  }
}
