-- ============================================================
-- inv-items-donated-unknown-fix.sql
-- One-time data correction, run AFTER migration 0153 (which
-- makes inv_items.is_donated nullable).
--
-- The 2026-07 historical import (0083) had to set every row's
-- donation status to true/false, but most rows in the source
-- spreadsheet never actually said either way — it defaulted the
-- rest to false, which quietly overstated confidence the register
-- never had. This corrects those back to NULL ("unknown") rather
-- than a guessed "No". (0 rows needed the opposite fix — every
-- row the sheet DID answer, 0083 already got right.)
--
-- Re-derived directly from Sparrow_Master_Asset_Log_2026.xlsx —
-- unknown means the row had no "Donated" column mark (X) and no
-- "donated"/"purchased" mention anywhere in its own Notes/Changes
-- text. Matches by (location, sub-location, description) — same
-- portable pattern as 0083's original import — not by row ID.
-- Idempotent: setting is_donated = NULL on an already-NULL row is
-- a harmless no-op, safe to re-run.
-- ============================================================

-- Unknown — no donation/purchase info in the original sheet (150 items)
UPDATE inv_items i
SET is_donated = NULL
FROM (VALUES
  ('Office Building', NULL, 'Books Inspirational'),
  ('Audrey — Remote', NULL, 'HP Laptop (Audrey)'),
  ('Audrey — Remote', NULL, 'Cell Phones'),
  ('Bethany — Remote', NULL, 'Lenovo ThinkPad (Bethany)'),
  ('Bethany — Remote', NULL, 'Backpack (Bethany)'),
  ('Office Building', 'Various', 'Dell Laptop (Loan - LCP participant)'),
  ('Lindy — Remote', NULL, 'Dell Laptop (Lindy)'),
  ('Susanna — Remote', NULL, 'Lenovo ThinkPad (Susanna)'),
  ('Susanna — Remote', NULL, 'Acer Aspire Laptop (Susanna)'),
  ('Susanna — Remote', NULL, 'ASUS Monitor (Susanna)'),
  ('Susanna — Remote', NULL, 'Logitech Mouse & Keyboard (Susanna)'),
  ('Office Building', 'Entry', 'Wooden Desk'),
  ('Office Building', 'Entry', 'Office Desk Chair (Audrey''s)'),
  ('Office Building', 'Entry', 'Desk Lamp'),
  ('Office Building', 'Entry', 'File Cabinets (1×4-drawer locking, 1×3-drawer non-locking)'),
  ('Office Building', 'Entry', 'Space Heater'),
  ('Office Building', 'Entry', 'Coat Rack'),
  ('Office Building', 'Entry', 'Brochure Holders'),
  ('Office Building', 'Main Room', 'TCL TV Mounted'),
  ('Office Building', 'Main Room', 'Sitting Chairs'),
  ('Office Building', 'Main Room', 'Curtains (11 pairs)'),
  ('Office Building', 'Main Room', 'Dry Erase Easel & Supplies'),
  ('Office Building', 'Main Room', 'HP Printer OfficeJet 8600 Plus'),
  ('Office Building', 'Main Room', 'HP Printer OfficeJet 8600'),
  ('Office Building', 'Main Room', 'HP Printer OfficeJet 4840'),
  ('Office Building', 'Main Room', 'Epson EcoTank ET-3958 Printer'),
  ('Office Building', 'Main Room', 'Small Bubble Glass Lamp'),
  ('Office Building', 'Main Room', 'Bookshelf'),
  ('Office Building', 'Main Room', 'Misc Books'),
  ('Office Building', 'Main Room', 'Blue Office Desk Chair'),
  ('Office Building', 'Main Room', 'End Table'),
  ('Office Building', 'Main Room', 'Couch'),
  ('Office Building', 'Main Room', 'Recliner'),
  ('Office Building', 'Main Room', 'Chairs (used, set 1)'),
  ('Office Building', 'Main Room', 'Chairs (used, set 2)'),
  ('Office Building', 'Main Room', 'Office Chairs'),
  ('Office Building', 'Main Room', 'Folding Table (big)'),
  ('Office Building', 'Main Room', 'Small Folding Table'),
  ('Office Building', 'Main Room', 'End Tables'),
  ('Office Building', 'Main Room', 'Mattress'),
  ('Office Building', 'Kitchen', 'Refrigerator'),
  ('Office Building', 'Kitchen', 'Microwave'),
  ('Office Building', 'Kitchen', 'Coffee Bar Table'),
  ('Office Building', 'Kitchen', 'Misc Kitchen Supplies'),
  ('Office Building', 'Kitchen', 'Green GE Double Oven'),
  ('Office Building', 'Prayer Room', 'Sitting Chairs'),
  ('Office Building', 'Prayer Room', 'Space Heater'),
  ('Office Building', 'Prayer Room', 'Footstool'),
  ('Office Building', 'Prayer Room', 'Folding Chairs (used, 4)'),
  ('Office Building', 'Prayer Room', 'Folding Chairs (new, 4)'),
  ('Office Building', 'Prayer Room', 'Vacuum — Eureka (small, prayer room closet)'),
  ('Office Building', 'Kids Play Room', 'Child''s Craft Table'),
  ('Office Building', 'Kids Play Room', 'Child''s Plastic Chairs'),
  ('Office Building', 'Kids Play Room', 'Sansui TV'),
  ('Office Building', 'Kids Play Room', 'Bookshelf (children''s)'),
  ('Office Building', 'Kids Play Room', 'Shelf with Toy Bins'),
  ('Office Building', 'Kids Play Room', 'Misc Children''s Books'),
  ('Office Building', 'Kids Play Room', 'Misc Children''s Toys'),
  ('Office Building', 'Kids Play Room', 'Beanbag Chair'),
  ('Office Building', 'Kids Play Room', 'Toy Box'),
  ('Office Building', 'Blue Office Shed', 'Plastic Sandwich Boards'),
  ('Office Building', 'Blue Office Shed', 'Popcorn Maker'),
  ('Office Building', 'Blue Office Shed', 'Popcorn Popper West Bend (used)'),
  ('Office Building', 'Blue Office Shed', 'Steel Pet Gate'),
  ('Office Building', 'Blue Office Shed', 'Portable AC Honeywell'),
  ('Office Building', 'Various', 'Portable AC Perfect Aire'),
  ('Office Building', 'Various', 'Portable AC Haire'),
  ('Office Building', 'Various', 'Honeywell Stand Fan'),
  ('Office Building', 'Various', 'SoundCore Bluetooth Speaker'),
  ('Office Building', 'Various', 'Igloo Ice Chest'),
  ('Office Building', 'Various', 'Wyze Security Camera'),
  ('Office Building', 'Various', 'Key Lockbox'),
  ('Office Building', 'Entry', 'Air Conditioner'),
  ('Office Building', 'Various', 'Play Pen / Baby Play Pen'),
  ('Office Building', 'Various', 'Security Camera Ring'),
  ('Office Building', 'Various', 'Security System Lorex'),
  ('Office Building', 'Various', 'Lamps (main & prayer room)'),
  ('Office Building', 'Various', 'Lamps'),
  ('Office Building', 'Various', 'Misc Household Decor (wall clocks, pictures, plants, etc.)'),
  ('Office Building', 'Various', 'Misc Office Supplies (nonconsumables)'),
  ('Office Building', 'Blue Office Shed', 'Small End Table'),
  ('Office Building', 'Various', 'Mobile Hot Spot'),
  ('Office Building', 'Various', 'Rugs (LR, Prayer Rm, Play Rm, Kitchen, Bathroom)'),
  ('Office Building', 'Various', 'Air Purifiers (off-site)'),
  ('Office Building', 'Various', 'Master Padlocks'),
  ('Office Building', 'Yard / Outside', 'Patio Table & 4 Chairs'),
  ('Office Building', 'Yard / Outside', 'Outside Play Structure'),
  ('Office Building', 'Yard / Outside', 'Steel Outdoor Chairs (blue)'),
  ('Office Building', 'Yard / Outside', 'Totes — Christmas / Holiday Decorations'),
  ('Office Building', 'Yard / Outside', 'Kids Outdoor Toys'),
  ('Office Building', 'Yard / Outside', 'Fence / Solar Lights (11 units, lumped)'),
  ('Outdoor Areas', 'Steel Shed (office)', 'Red Push Mower & Bag'),
  ('Outdoor Areas', 'Steel Shed (office)', 'Echo LM-2119SP Self-Propelled Lawn Mower'),
  ('Outdoor Areas', 'Steel Shed (office)', 'Green Electric Weed Trimmer'),
  ('Outdoor Areas', 'Steel Shed (office)', 'Pressure Washer (Honda)'),
  ('Outdoor Areas', 'Steel Shed (office)', 'Weed Eaters (1 electric, 1 battery)'),
  ('Outdoor Areas', 'Steel Shed (office)', '24" Libman Push Broom'),
  ('Outdoor Areas', 'Timber Shed', 'Orange Ridgid Step Ladder'),
  ('Outdoor Areas', 'Behind the Sheds', 'Wheelbarrows'),
  ('Outdoor Areas', 'Behind the Sheds', 'Wheelbarrow (new, 2021)'),
  ('Outdoor Areas', 'Behind the Sheds', 'Extension Ladder'),
  ('Outdoor Areas', 'Behind the Sheds', 'Silver Step Ladder'),
  ('Outdoor Areas', 'Behind the Sheds', 'Electric Chainsaws (×2, 2021)'),
  ('Outdoor Areas', 'Behind the Sheds', 'Wood Chipper DR Equipment'),
  ('Outdoor Areas', 'Steel Shed (laundry room)', '56V EGO Battery Lawn Trimmer'),
  ('Outdoor Areas', 'Steel Shed (laundry room)', 'EGO Battery Hedge Trimmer'),
  ('Outdoor Areas', 'Steel Shed (laundry room)', 'Electric Shop Vac (dry)'),
  ('Outdoor Areas', 'Steel Shed (laundry room)', 'Homelite Gas Chainsaw (in box)'),
  ('Outdoor Areas', 'Steel Shed (laundry room)', 'Submersible Pump'),
  ('Outdoor Areas', 'Steel Shed (laundry room)', 'Ridgid Sander'),
  ('Outdoor Areas', 'Steel Shed (laundry room)', 'Ridgid Storage Totes Set'),
  ('Outdoor Areas', 'Steel Shed (laundry room)', 'Ridgid HandVac Cordless'),
  ('Outdoor Areas', 'Steel Shed (laundry room)', 'Ridgid Hand Blower Cordless'),
  ('Outdoor Areas', 'Steel Shed (laundry room)', 'Ridgid Kit (drill, sawzall, skillsaw, impact, flashlight, battery charger)'),
  ('Outdoor Areas', 'Steel Shed (laundry room)', 'Stihl Backpack Blower'),
  ('Laundry Room', NULL, 'Washer'),
  ('Laundry Room', NULL, 'Dryer'),
  ('Laundry Room', NULL, 'Maytag Washer'),
  ('Service Volunteer Trailer', 'Bathroom', 'Shower Curtain'),
  ('Service Volunteer Trailer', 'Childcare Room', 'Misc Toys (childcare)'),
  ('Service Volunteer Trailer', 'Kitchen', 'Baby Gate'),
  ('Service Volunteer Trailer', 'Kitchen', 'Travel Booster Seat'),
  ('Service Volunteer Trailer', 'Kitchen', 'Bar Stools'),
  ('Service Volunteer Trailer', 'Living Room', 'Couch'),
  ('Service Volunteer Trailer', 'Various', 'Curtains (8 sets, throughout)'),
  ('Goshen House', 'Kitchen', 'Misc Kitchen Supplies'),
  ('Goshen House', 'LR', 'Couch'),
  ('Goshen House', 'LR', 'Standing Floor Lamp'),
  ('Goshen House', 'LR', 'Rocking Chair & Footstool'),
  ('Goshen House', 'LR', 'Goshen LR Curtains'),
  ('Goshen House', 'Various', 'Rugs (8, throughout — LR, Kitchen, Hall, Entry, Bathrooms)'),
  ('Goshen House', 'Various', 'Misc Household Decor (whole house)'),
  ('Shiloh House', 'Kids'' Room', 'Bunk Beds'),
  ('Shiloh House', 'Kids'' Room', 'Kids Dresser'),
  ('Shiloh House', 'Kids'' Room', 'Bookshelf'),
  ('Shiloh House', 'Kitchen', 'Microwave (Shiloh House)'),
  ('Shiloh House', 'Kitchen', 'Misc Kitchen Supplies'),
  ('Shiloh House', 'Kitchen', 'Kitchen Table'),
  ('Shiloh House', 'Kitchen', 'Kitchen Chairs'),
  ('Shiloh House', 'Kitchen', 'Pantry Unit'),
  ('Shiloh House', 'LR', 'Couch'),
  ('Shiloh House', 'LR', 'Chair (LR)'),
  ('Shiloh House', 'LR', 'Footstool'),
  ('Shiloh House', 'LR', 'Coffee Table'),
  ('Shiloh House', 'Master Bedroom', 'Black Dresser'),
  ('LCP Home (RV)', NULL, 'Baby Bath'),
  ('LCP Home (RV)', NULL, 'Step Stool'),
  ('LCP Home (RV)', 'Kitchen', 'Misc Kitchen Supplies'),
  ('LCP Home (RV)', 'Porch', 'Camping Chair'),
  ('Outdoor Areas', 'Steel Shed (office)', 'Small Hand Tools — lump sum (hammers, wrenches, screwdrivers, etc.)')
) AS v(loc_name, sub_loc_name, description)
JOIN inv_locations l ON l.name = v.loc_name
LEFT JOIN inv_sub_locations sl ON sl.location_id = l.id AND sl.name = v.sub_loc_name
WHERE i.location_id = l.id
  AND i.description = v.description
  AND (i.sub_location_id = sl.id OR (i.sub_location_id IS NULL AND sl.id IS NULL));

