-- Sparrow — LCP: pre-fill Monday Mentoring content for all 48 sessions, and create
-- the 44 session rows that did not exist yet (only Foundation 1-4 were seeded before).
-- Source: Shelly's "Mentor Conversation Guide" (all 48 sessions, in sequence) — parsed
-- and verified word-for-word against the source before generating this file (see
-- Post Day 2 Ingest/Susanna LCP curriculum for the original .docx).
-- Depends on: 0085_lcp_session_structure.sql (mentor_brief/mentor_handout_echo/mentor_going_deeper columns)
-- Safe to re-run: existing sessions (1-4) only get their Monday fields updated; new
-- sessions (5-48) are only inserted if a row with that session_number doesn't already exist.

-- Session 1 (Foundation · local #1) — "What does your house look like right now?"
UPDATE lcp_sessions SET
  mentor_brief = '<p>This is the opening session of the entire year. The participant has just been introduced to the house metaphor and drawn her first house drawing — one word per room for how each area of her life feels right now. This drawing will be kept all year and returned at graduation. Your most important job today is simply to open the relationship. She may be guarded. She may be surprised by what she felt in the drawing activity. Ask gently. Don’t push. And find out: is she in? Does she want to do this work?</p>',
  mentor_handout_echo = '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>If your life were a house right now, what one word would you use to describe it overall?</li><li>What parts of your life feel safe or okay to you right now?</li><li>Is there a part of your life you tend to avoid thinking about?</li><li>What do you hope looks different one year from now?</li></ol>',
  mentor_going_deeper = '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>When you drew your house, was there a room that surprised you — one you labeled something you weren’t expecting?</li><li>Is there a room in your house that you’ve never let anyone into? Not even God?</li><li>What would it mean for this year to be different from other times you’ve tried to change something?</li><li>If someone who knew you completely drew your house for you — what room do you think they’d be most concerned about?</li></ul>'
WHERE session_number = 1;

-- Session 2 (Foundation · local #2) — "Who told you that about yourself?"
UPDATE lcp_sessions SET
  mentor_brief = '<p>This session went into identity — specifically the lies women carry about themselves and where those lies came from. The participant worked through a two-column exercise: on the left, things she has actually believed about herself; on the right, what God says instead. She also spoke truth declarations aloud with the group. This conversation is a chance to go deeper on what she wrote in that left column, which is often more raw than what she shared in group.</p>',
  mentor_handout_echo = '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What is one thing you believed about yourself for years that you are starting to question?</li><li>Where did that belief come from? Who or what planted it?</li><li>What would it feel like if that belief was not true?</li></ol>',
  mentor_going_deeper = '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What did you write in the left column that you’ve never said out loud to anyone?</li><li>Who is the voice you hear most when you think about who you are? What does it say?</li><li>Of everything in the right column — the truths God says about you — which one do you find hardest to believe? Why that one?</li><li>If you woke up tomorrow and fully believed the right column was true — what would be the first thing that would change in how you live?</li></ul>'
WHERE session_number = 2;

-- Session 3 (Foundation · local #3) — "What is my foundation made of?"
UPDATE lcp_sessions SET
  mentor_brief = '<p>This session named the false foundations women commonly build on: approval, relationships, control, survival, performance, substances. Participants did a physical exercise with cards on paper versus a solid book, and checked which false foundations feel familiar to them from a list on the handout. The honest confession of what one has been building on is often clearer in one-on-one conversation than in a group.</p>',
  mentor_handout_echo = '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What have you built your sense of security on in the past?</li><li>When that thing was taken away or failed — what happened inside you?</li><li>What would it look like to build your life on something that doesn’t move?</li></ol>',
  mentor_going_deeper = '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>Which of the false foundations on the list felt most like you? Did more than one?</li><li>Is there a false foundation you are still building on right now — even while you’re in this program?</li><li>What does it actually look like, in a practical day, to build on Christ instead? What would be different about a Tuesday?</li><li>What is the storm that has hit your house the hardest? What held, and what fell?</li></ul>'
WHERE session_number = 3;

-- Session 4 (Foundation · local #4) — "Laying the first stone"
UPDATE lcp_sessions SET
  mentor_brief = '<p>This closing session of the Foundation unit was ceremonial. Participants looked at their Session 1 house drawing, made a written covenant commitment, wrote their name and an intention on a stone, and placed it in the center of the table as a group act of commitment. These stones are kept all year and returned at graduation. Ask her about her stone — the word she chose matters, and this is a good conversation to have in private.</p>',
  mentor_handout_echo = '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What is one thing you are choosing to let go of as a foundation?</li><li>What is one truth about yourself that you are choosing to believe — even if it feels hard?</li><li>What do you want your house to feel like one year from now?</li></ol>',
  mentor_going_deeper = '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What word or phrase did you write on your stone? Why did you choose that one?</li><li>What was it like to place the stone in the center with everyone? Did anything surprise you about that moment?</li><li>Read me the covenant you wrote. What part of it feels most true? Which part feels most out of reach?</li><li>What is the one thing that would make you want to give up on this commitment before the year is out? What will you do when that thing comes?</li></ul>'
WHERE session_number = 4;

-- Session 5 (Basement · local #1) — "What’s in the basement?"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Basement'), 5, 5, 'What’s in the basement?', 'Deuteronomy 30:19', '<p>This opening Basement session introduced the idea that we all carry things we never chose — patterns handed down through family lines, survival strategies we absorbed before we were old enough to evaluate them. The group began to name what’s in their basement and were introduced to the genogram exercise. This is often the session where women feel both recognized (someone finally named it) and afraid (I’m not sure I want to look). Watch for both.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What comes to mind when you think about the word ‘basement’ in your own life?</li><li>What patterns did you grow up around that you’ve found yourself repeating?</li><li>Is there something in your basement that you’ve been aware of but haven’t wanted to look at directly?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What is the thing in your basement that you are most afraid of finding there?</li><li>Which family pattern do you feel most at risk of passing to your children?</li><li>Has anyone ever named what was in your family before? Or has it always been the unspoken thing?</li><li>What would it mean for you to be the person in your family who actually looked at it?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 5);

-- Session 6 (Basement · local #2) — "Building the genogram"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Basement'), 6, 6, 'Building the genogram', 'Deuteronomy 30:19', '<p>The group built their genograms in this session — a visual map of their family across three generations, marking patterns of addiction, abuse, abandonment, mental illness, and also strength, faith, and resilience. This is often the most emotionally activating session of the unit. The participant has now seen her family laid out visually. Ask with care. She may have seen things she wasn’t expecting. She may also have found strengths she hadn’t noticed before.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What was it like to put your family map on paper?</li><li>What patterns did you notice showing up across generations?</li><li>Was there anything on the map that surprised you — something harder or more hopeful than you expected?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What did you see on your genogram that you have never said out loud to anyone?</li><li>Where do you see yourself on that map? Which pattern are you carrying?</li><li>Were there people on your map who broke a cycle before you? What did it cost them?</li><li>What strength did you find that you hadn’t recognized as inherited?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 6);

-- Session 7 (Basement · local #3) — "What does this mean for me?"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Basement'), 7, 7, 'What does this mean for me?', 'Deuteronomy 30:19', '<p>This session asked women to look at their completed genogram as a mirror — not just a history but a picture of patterns that may already be active in their own life and their children’s lives. The three handout prompts moved from seeing to naming to facing the forward risk. This is the turning point of the unit. Women who were willing to look at the past are now being asked to look at the present and the future. That takes a different kind of courage.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Where do you see yourself in your family picture? Are you carrying something that was carried before you?</li><li>What has already shown up in your own life from what you saw on your map?</li><li>Is there anything on your map that you are at risk of passing to your children if nothing changes?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What is the specific pattern you are most determined not to pass on? Can you say it out loud and name it clearly?</li><li>Have you noticed the pattern activating in you recently — in a specific situation with your child or someone close?</li><li>What is the pause that could interrupt it? What would three seconds of choice look like for you?</li><li>Who in your life knows you’re trying to break this pattern and can help hold you to it?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 7);

-- Session 8 (Basement · local #4) — "I don’t have to pass this on"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Basement'), 8, 8, 'I don’t have to pass this on', 'Jeremiah 29:11', '<p>The closing Basement session was ceremonial. Women wrote one pattern on a slip of paper and placed it in a bowl as a physical act of release. They also wrote a hope to carry forward. This was intentionally a time of grieving as well as releasing — the two are not the same thing, and the session honored both. Ask her about what she released and what she is carrying forward. The covenant declarations from this session are significant.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What is one thing you saw this month that you had never seen clearly before?</li><li>What is one thing you are choosing not to pass on to your children?</li><li>What does ‘a hope and a future’ feel like to you right now?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What did you write on your slip of paper — the thing you released? Are you willing to say it out loud here?</li><li>What is the hope you wrote that you are carrying forward? Do you believe it yet, or are you holding it by faith?</li><li>What did it feel like to place the slip in the bowl? Was the release real for you, or did something in you hold back?</li><li>What would need to be true six months from now for you to say: this pattern really did stop with me?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 8);

-- Session 9 (Front Door · local #1) — "What does your front door say?"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Front Door'), 9, 9, 'What does your front door say?', 'Proverbs 4:23', '<p>This session introduced the front door as a metaphor for how a woman manages the boundary between her inner life and the outside world. Many women in this program have never had permission to have a door at all. Some have lived with doors wide open to anyone; others have doors so locked that no one can get in. This first conversation is about beginning to see what her current door actually looks like — not what she wishes it looked like.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Growing up, did you have permission to have limits? What happened when you tried to set one?</li><li>What does the word ‘boundary’ feel like to you? Selfish? Safe? Foreign? Something else?</li><li>Is there an area of your life right now where you have no door — where you let in everything? Or one where the door is too shut?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>Who has a key to your inner life right now — who can walk in whenever they want? Did you give them that key or did they take it?</li><li>Is there a specific person or situation where you know you need a door but don’t have one yet?</li><li>What do you fear will happen if you start setting limits with that person?</li><li>What would it mean to you to believe that having a door is not selfish — that God designed you to have one?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 9);

-- Session 10 (Front Door · local #2) — "Healthy boundaries — locks and keys"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Front Door'), 10, 10, 'Healthy boundaries — locks and keys', 'locks and keys', '<p>This session got practical: what does a boundary actually look like, how do you say it, and what do you do when it’s ignored? Participants practiced the language of limits in group — saying hard things out loud in a safe room before they need to say them in a real situation. The homework from this session often includes a specific situation the participant identified where she needs to hold a limit. Ask her about that.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Which of the four reasons boundaries feel hard feels most like yours: guilt (it’s selfish), fear (something bad will happen), unfamiliarity (I don’t know how), or history (I’ve tried and it didn’t work)?</li><li>Is there a relationship or situation in your life right now where you need a boundary you don’t have?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>If you could say one thing clearly to one person in your life — something you’ve been swallowing — what would it be?</li><li>What do you think would actually happen if you said it? Is that fear realistic or is it the old story running?</li><li>Have you ever successfully held a limit with someone? What did that take? What did you learn?</li><li>What is the smallest boundary you could practice this week — a low-stakes one, just to feel what it’s like?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 10);

-- Session 11 (Living Room · local #1) — "What love was designed to look like"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Living Room'), 11, 11, 'What love was designed to look like', 'Romans 12:9–10', '<p>This opening session set the standard — what does genuine love actually look like? Not sentiment, but Romans 12 love: sincere, devoted, honoring. The session also named the three patterns that look like love but aren’t: codependency, people-pleasing, and enmeshment. These were framed as survival strategies, not character flaws. Watch for recognition — this session often lands with particular force.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What does love actually look like in the closest relationships in your life right now? Does it look like Romans 12?</li><li>Of the three patterns named — codependency, people-pleasing, enmeshment — which one feels most familiar to you?</li><li>Where did you first learn that version of love?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>Can you think of a specific relationship where one of those patterns is most active right now?</li><li>What did it cost you to love the way you’ve been loving? What have you lost?</li><li>What would a relationship look like where you were genuinely honoring someone — and genuinely being honored back?</li><li>Have you ever experienced that kind of relationship, even briefly? What was it like?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 11);

-- Session 12 (Living Room · local #2) — "The patterns that look like love but aren’t"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Living Room'), 12, 12, 'The patterns that look like love but aren’t', 'Proverbs 4:23', '<p>This session went deeper into relational patterns — specifically control and isolation were named alongside the session 1 patterns. Women were asked: where did I learn this? The ‘who were you before’ question was introduced — who were you before this pattern took hold? This session often surfaces significant pain around primary relationships — often a parent or a significant partner.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What is one relational pattern you’ve carried for a long time that you’re starting to see clearly?</li><li>Where did that pattern come from — what was the relationship or the moment that installed it?</li><li>What has it cost you?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>Who were you before that pattern took hold? Can you remember a version of yourself that related differently?</li><li>What would it mean to you to say: I am not this pattern. This is something I learned, and it can be unlearned?</li><li>Is there a specific person in your life who most activates this pattern in you?</li><li>What would it look like to respond differently with that person — even once, even imperfectly?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 12);

-- Session 13 (Living Room · local #3) — "What healthy actually feels like from the inside"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Living Room'), 13, 13, 'What healthy actually feels like from the inside', 'Galatians 5:22–23', '<p>This session gave women a picture of what a healthy relationship feels like — not just what it looks like from the outside. Five qualities were explored. The session also raised the uncomfortable truth that healthy can feel unfamiliar or even suspicious to someone whose nervous system was shaped by chaos. This is an important conversation — ask her what healthy feels like for her, not just what she thinks it should look like.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Of the five qualities of a healthy relationship discussed, which one is most present in your closest relationships right now? Which is most absent?</li><li>Does healthy ever feel boring or suspicious to you? What does that tell you?</li><li>What is one relationship in your life right now that you’d describe as genuinely healthy?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What does your nervous system do when a relationship is calm and consistent? Does peace feel safe or does it feel like something’s wrong?</li><li>Have you ever found yourself creating chaos in a relationship that was going well? What was that about?</li><li>What would it take for you to begin to trust a relationship that is genuinely good?</li><li>What does a healthy relationship with God feel like to you — does the same suspicion show up there?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 13);

-- Session 14 (Living Room · local #4) — "The signs you are in something unhealthy"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Living Room'), 14, 14, 'The signs you are in something unhealthy', 'John 8:32', '<p>This session named four patterns of unhealthy relationships: control and unpredictability, isolation, gradual erosion of self, and contempt. It also made an important distinction between unhealthy and dangerous — some relationships need to change, some need to end, and some require safety planning. This conversation requires care. If she is in a currently dangerous situation, your referral resources should be ready.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Which of the four patterns — control/unpredictability, isolation, erosion of self, contempt — have you experienced?</li><li>Is there a current relationship that shows any of these patterns?</li><li>What has kept you in a relationship that you knew wasn’t healthy?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>On a scale of unhealthy to dangerous — where would you honestly place this relationship?</li><li>What do you tell yourself that makes it easier to stay? Is that story true?</li><li>Who knows the real story of this relationship? Has anyone ever seen the actual version of it?</li><li>What would need to be different for you to feel safe enough to change something? What is one step you could take?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 14);

-- Session 15 (Living Room · local #5) — "Learning to sit together through the hard things"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Living Room'), 15, 15, 'Learning to sit together through the hard things', 'John 15:12', '<p>This session got practical about conflict and vulnerability. Women practiced specific conversations — how to say hard things, how to re-engage after disconnection, how to be vulnerable in proportion to what a relationship has earned. The scenario practice is often more impactful in private conversation because she can name the actual relationships involved rather than working with fictional examples.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What is your default response when conflict comes up in a close relationship — do you fight, flee, freeze, or fix?</li><li>Is there a relationship where you know something needs to be said but you haven’t said it?</li><li>What makes vulnerability feel safe or unsafe for you?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>Think about the specific relationship where something needs to be said. What are you afraid will happen if you say it?</li><li>What has happened in the past when you’ve tried to say something hard? What did you learn from that?</li><li>What would it look like to be vulnerable in proportion to what this relationship has actually earned — not more, not less?</li><li>Is there someone in your life who has done conflict well with you — who has stayed through a hard conversation? What did you notice about how they did it?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 15);

-- Session 16 (Living Room · local #6) — "Making wise decisions and building toward what is good"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Living Room'), 16, 16, 'Making wise decisions and building toward what is good', 'Ruth 1:16', '<p>This closing Living Room session gave women four questions for evaluating relationships and making wise decisions. Forgiveness was named as releasing a debt — not reconciliation or trust. Green flags were explored alongside red ones. The Coat of Arms artifact was created. This is often a session where women have made or are about to make a significant decision about a relationship. Ask what she is building toward.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What is one relationship you feel clearer about after this unit?</li><li>What does forgiveness actually mean for you — and is there someone you’re working on forgiving?</li><li>What is one green flag you are looking for in the relationships you let close?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>Is there a relationship decision in front of you right now? What are the four questions telling you?</li><li>What does forgiveness feel like in your body when you’re working toward it — what is the actual experience?</li><li>Who are you building toward? What does the living room you want look like — who is in it, what does it feel like?</li><li>What is one thing from this unit that you want to carry into how you live from here?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 16);

-- Session 17 (Kitchen & Dining · local #1) — "What are you feeding yourself?"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Kitchen & Dining'), 17, 17, 'What are you feeding yourself?', 'Deuteronomy 8:3', '<p>This session opened with physical nourishment but quickly moved to the whole person — what we feed ourselves emotionally, spiritually, and relationally. Women were asked to assess their nourishment honestly: what genuinely sustains them vs. what depletes them even when it feels satisfying in the moment. Body, sleep, and daily rhythm were also explored.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What did nourishment look like in your home growing up? Was there enough? Was the table a safe place?</li><li>What do you tend to reach for when you are stressed, sad, or overwhelmed?</li><li>What is one way you have treated your body well recently — or one way you have neglected it?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What does your actual daily rhythm look like right now — food, sleep, movement, quiet?</li><li>What are you feeding yourself emotionally? What are the primary things going in on a regular basis?</li><li>Is there one thing you are taking in that you know isn’t nourishing you but you haven’t stopped?</li><li>What does it mean to you that God provides a table — that nourishment is something He offers, not something you always have to generate yourself?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 17);

-- Session 18 (Kitchen & Dining · local #2) — "The table we grew up at"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Kitchen & Dining'), 18, 18, 'The table we grew up at', 'Luke 15:20', '<p>This session explored the family table — the messages about food, belonging, welcome, and worthiness that were absorbed growing up. For many women in this program, the table growing up was a place of tension, lack, or unpredictability. This conversation should be approached gently — there may be food insecurity, trauma around meals, or simply a profound absence of warmth.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Have you ever experienced food insecurity? What did that feel like, and how did it shape you?</li><li>What does your sleep look like right now? What gets in the way of genuinely resting?</li><li>What is one practical change — around food, sleep, or daily rhythm — that you could make this week?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What was the table actually like in your home growing up? Was there warmth there, or was it a place of tension?</li><li>What messages did you absorb at that table about your own worth — about whether you belonged, whether there was room for you?</li><li>Do any of those messages still show up at your own table now — in how you feed your children or yourself?</li><li>What would it mean to you to sit at a table where you were genuinely welcome, genuinely seen, genuinely fed?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 18);

-- Session 19 (Kitchen & Dining · local #3) — "Setting a table worth sitting at"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Kitchen & Dining'), 19, 19, 'Setting a table worth sitting at', 'Psalm 23:5', '<p>This session shifted to the table the participant is setting now — for her children, for her household. What kind of atmosphere is she creating? What does mealtime look like in her home, and what does she want it to feel like? This is often a session where women feel both conviction and hope.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What was the table like in your home growing up? Was there a regular family meal?</li><li>What does mealtime look like in your home right now? What is the atmosphere?</li><li>What is one thing you want your children to remember about your table?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>If your children described your table in one word, what do you think they’d say?</li><li>What do you want that word to be?</li><li>What is the gap between those two things — and what is one thing you could do to close it?</li><li>What does God setting a table for you — even in the presence of your enemies — actually mean for how you live right now?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 19);

-- Session 20 (Kitchen & Dining · local #4) — "A place at the table"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Kitchen & Dining'), 20, 20, 'A place at the table', 'Revelation 19:9', '<p>The closing session of the Kitchen unit moved to the ultimate table — the invitation to belong, permanently and without performance, at God’s table. It also looked back at Phase 2 as a whole. This is the last session of the Heart of the Home phase. A good moment to ask: what has she taken from these months? What has landed most?</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Is there a gratitude practice you already use at your table — or one you’d like to begin?</li><li>What is one thing you want your children to learn from the way you feed your family?</li><li>This is the end of Phase 2. What is the biggest thing you are taking from these months?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>Do you genuinely believe there is a place at the table for you — not earned, not conditional, just there?</li><li>What makes that hard to believe? What is the voice that says you don’t belong?</li><li>What is the most significant thing that has changed in you since the beginning of Phase 2?</li><li>What do you still want to change in the Heart of the Home — in your relationships, your nourishment, or how you hold your boundaries?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 20);

-- Session 21 (Bathroom · local #1) — "The mirror — seeing ourselves clearly"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Bathroom'), 21, 21, 'The mirror — seeing ourselves clearly', 'seeing ourselves clearly', '<p>This session asked women to stand in front of the mirror honestly — who do you see? What do you believe about what you see? The double bind of shame was named: the mirror lies to us and we know it, but we also believe it. Secrets and the weight they carry were also discussed. This is often a conversation where things surface that have never been said before. Hold the space carefully.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Have you ever carried a secret so long that you forgot what it felt like to not carry it?</li><li>Can you identify a double bind in your own life — something you can’t talk about because of what people would think?</li><li>What would it feel like to be fully known — every part of you — and still loved?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What do you see when you look in the mirror? Not what you think you’re supposed to say — what do you actually see?</li><li>What is the thing about yourself that you are most afraid someone would find out?</li><li>Has there ever been someone who knew that thing and loved you anyway? What was that like?</li><li>What would it mean for you to actually believe that God sees all of it — and is not horrified?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 21);

-- Session 22 (Bathroom · local #2) — "The wash — confession and cleansing"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Bathroom'), 22, 22, 'The wash — confession and cleansing', 'confession and cleansing', '<p>This session explored confession — not as punishment or performance, but as the actual mechanism of freedom. The difference between shame and repentance was named carefully. Many women have experienced religion as shame-adding rather than shame-removing. This conversation may surface significant experiences of religious harm or conditional grace. Approach gently and without defensiveness.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Has the Christianity you have encountered felt more like something that adds to your shame or removes it?</li><li>What is the difference between shame and repentance in your own experience?</li><li>Is there something you have carried that you believed was beyond forgiveness?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What does confession feel like in your body — is it relief, or is it dread?</li><li>What is the thing you most need to bring into the light right now? You don’t have to say it, but is it there?</li><li>Have you ever experienced genuine absolution — the sense that something was actually washed, not just managed?</li><li>What would it mean for that specific thing to be clean — genuinely, permanently clean?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 22);

-- Session 23 (Bathroom · local #3) — "Walking out clean"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Bathroom'), 23, 23, 'Walking out clean', '2 Corinthians 5:17', '<p>The closing Bathroom session asked: what does life look like after cleansing? How do you hold a new identity when the old one keeps calling? Practical rhythms of honest prayer and accountability were discussed. The Walking Out drawing artifact was created. This is often a session where women feel both free and fragile — something has been released and they’re not sure how to maintain it.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What does a regular practice of honest prayer with God look like for you right now — or what would you want it to look like?</li><li>Do you have a trusted person who knows your real story and prays with you?</li><li>What does ‘go and live clean’ look like practically in your life right now?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What is the old identity — the old voice — that comes back most loudly? What does it say?</li><li>What do you do when it comes back? What would you want to do instead?</li><li>Is there a rhythm or practice you could put in place this week that would help you hold the new identity?</li><li>Who knows you well enough to say: ‘Hey, that’s the old you talking. That’s not who you are anymore’?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 23);

-- Session 24 (Master Bedroom · local #1) — "He makes me lie down"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Master Bedroom'), 24, 24, 'He makes me lie down', 'Psalm 23:1–2', '<p>Rest as a spiritual discipline — not a reward for finished work. This session asked why so many women have never learned to genuinely stop, and named three reasons rest doesn’t feel available: it doesn’t feel safe, it feels selfish, or it feels impossible. For women in transitional housing, rest is often a luxury that has never been available. This is a tender conversation. Don’t rush it.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>When is the last time you genuinely rested? What did it feel like?</li><li>Which feels most familiar: rest doesn’t feel safe, rest feels selfish, or rest feels impossible given your circumstances?</li><li>What would you need to believe — about God, yourself, or your circumstances — for rest to feel available to you?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What is the thing that most prevents you from stopping — the internal voice or the external demand?</li><li>Have you ever experienced genuine rest — body, mind, spirit? What was the context?</li><li>What does it mean to you that God ‘makes’ you lie down — that He doesn’t wait for you to figure it out?</li><li>What is one small act of rest you could give yourself this week, without earning it first?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 24);

-- Session 25 (Master Bedroom · local #2) — "The way it was meant to be"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Master Bedroom'), 25, 25, 'The way it was meant to be', 'Genesis 1:31', '<p>This session covered God’s original design for sexuality — good, sacred, not shameful. Shame entered in Genesis 3; it was not the design. For many women in this program, their experience of sexuality has been shaped by violation, exploitation, or shame-based religion rather than by God’s original intent. This conversation may be one of the most significant of the year. Approach with great care and gentleness.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What messages did you receive growing up about your body and sexuality?</li><li>What is your honest reaction to hearing that God designed sexuality as good — not shameful?</li><li>What would change for you if you genuinely believed your body is good — made with intention and worthy of care?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What has your experience of sexuality actually been? You don’t have to go into detail, but: has it been something that has given you life, or taken it?</li><li>What do you believe God thinks about what has happened to you in this area — or what you have done?</li><li>What does it mean to you that the shame was not the design — that it was not supposed to be this way?</li><li>What would it mean to receive your body back — as something that is yours, that is good, that deserves care?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 25);

-- Session 26 (Master Bedroom · local #3) — "Covenant, purity and moving forward"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Master Bedroom'), 26, 26, 'Covenant, purity and moving forward', 'Hebrews 13:4', '<p>This session covered purity as protection of worth rather than shame-based restriction. Covenant love was explored — what it looks like to be fully known and fully chosen. Many women in this program have experienced the opposite of covenant — being used, abandoned, or given false promises. This conversation should be honest and free of moralism. The goal is dignity, not performance.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>How has the word ‘purity’ been used in your experience? Was it a word of shame or a word of worth?</li><li>What would it mean to you to believe you are worth protecting — that you are not available to anyone who wants access?</li><li>What is one boundary or standard you want to hold going forward in this area of your life?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What does the word ‘covenant’ bring up for you — has anyone ever kept one with you?</li><li>What would it feel like to be fully known by a person who fully stayed? Have you ever had a glimpse of that?</li><li>What do you want for yourself in this area of your life going forward? Not what you think you should want — what you actually want?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 26);

-- Session 27 (Master Bedroom · local #4) — "Healing from sexual shame"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Master Bedroom'), 27, 27, 'Healing from sexual shame', 'Psalm 147:3', '<p>This session addressed sexual shame directly — the specific and unique power of shame in this area, and Jesus’ response to the woman who reached for his cloak. The wound was named, and the possibility of healing was offered. This is one of the most sensitive sessions in the entire curriculum. Many women in this program carry violation, abuse, or exploitation they have never spoken of to another person. Move slowly.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Have you ever had someone bear witness to your wound in this area — someone who knew and did not run?</li><li>What has shame told you about yourself in the area of sexuality?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>Is there something in this area that you have never said out loud to another person?</li><li>What do you believe God’s response would be if you brought that specific thing to Him — not in general, but that specific thing?</li><li>What would it mean for the wound to be healed — not forgotten, but genuinely no longer defining you?</li><li>Is there a next step in your healing that you know you need to take but have been afraid to take? What is it?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 27);

-- Session 28 (Master Bedroom · local #5) — "Go in peace — and give your children something different"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Master Bedroom'), 28, 28, 'Go in peace — and give your children something different', 'and give your children something different', '<p>The closing Master Bedroom session moved from the participant’s healing to its forward reach — what heals in her reaches her children. The Letter to My Child artifact was written. This is often a session of significant emotion. She may have written things in that letter that she has never said. Ask about the letter gently. This is also a good time to ask about the overall arc of healing she sees herself in.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What do you most want your children to believe about their bodies and about themselves as they grow up?</li><li>What is the conversation about bodies or sexuality that you most want to have with your children — that you didn’t get to have with someone?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What did you write in your Letter to My Child? Is there a sentence from it you’d be willing to read aloud?</li><li>What is the thing in that letter that cost you the most to write?</li><li>When you imagine your child growing up with what you’re building now — what do you see for them that is different from what you had?</li><li>What does going in peace actually feel like right now? Are you closer to it than you were a month ago?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 28);

-- Session 29 (Kids’ Bedroom · local #1) — "Who this child is"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Kids’ Bedroom'), 29, 29, 'Who this child is', 'Psalm 127:3', '<p>This session covered child development by stage and the 30% repair rule — that being good enough and repairing when you’re not is the actual standard, not perfection. Secure attachment was discussed. This session can be both relieving (I don’t have to be perfect) and painful (I didn’t get that). Ask about both.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What stage is your child in right now? Does anything about their development feel confusing or hard to manage?</li><li>What is something you do — even imperfectly — that you think creates security for your child?</li><li>How does it feel to hear that 30% good enough plus repair is the actual standard?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What did secure attachment look like — or not look like — in your own childhood?</li><li>What does repair look like in your relationship with your child? Can you give an example of a time you got it wrong and came back?</li><li>What is the thing about your child that you find hardest to understand or connect with?</li><li>What would you want your child to say about you, looking back at this season of their life?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 29);

-- Session 30 (Kids’ Bedroom · local #2) — "Not the way I was parented"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Kids’ Bedroom'), 30, 30, 'Not the way I was parented', 'Proverbs 22:6', '<p>The four parenting styles were covered — authoritarian, authoritative, permissive, uninvolved. The cycle-breaking process was named as three steps: awareness, the pause, and the choice. Women were asked which style they received and which they default to under stress. This is often where the Basement unit and the Kids’ Bedroom unit connect most directly. The specific stress trigger is often the key.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Which parenting style did you primarily receive growing up? What did it give you, and what did it cost you?</li><li>Which style do you default to under stress? Is it the same as the one you received?</li><li>Where is your hardest trigger — what situation most activates the old pattern in your parenting?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>When that trigger activates, what happens in your body before you respond?</li><li>What is the pause that could interrupt it for you specifically? What would three seconds of choice look like?</li><li>Is there a moment in the past month where you paused and chose differently? What happened?</li><li>What is the parenting you wish you had received that you are trying to give? Can you name it specifically?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 30);

-- Session 31 (Kids’ Bedroom · local #3) — "What your child is absorbing"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Kids’ Bedroom'), 31, 31, 'What your child is absorbing', 'Deuteronomy 6:5–7', '<p>This session was built around three questions every child is asking: Am I safe? Am I loved? Am I capable? Women assessed their home against those three questions honestly. This is often where guilt surfaces — not as condemnation but as information. This conversation should move quickly from guilt to agency: what’s one thing she can change?</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Which of the three questions — Am I safe? Am I loved? Am I capable? — do you think your child is asking most urgently right now?</li><li>What does your home currently answer well? Where is the gap?</li><li>What is one specific, small change you can make this week that would help answer one of those questions better?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>If your child could see inside your home — the emotional atmosphere, not just the physical space — what would they see?</li><li>What is the thing your child absorbs from you that you are most proud of?</li><li>What is the thing they absorb that concerns you most?</li><li>What is the one change, above all others, that would most change the atmosphere of your home?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 31);

-- Session 32 (Kids’ Bedroom · local #4) — "Correction that builds"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Kids’ Bedroom'), 32, 32, 'Correction that builds', 'Hebrews 12:11', '<p>This session covered the four discipline tools: natural consequences, logical consequences, time-in, and problem-solving together. The key distinction was discipline vs. punishment — what builds vs. what damages. Women developed a discipline plan. This conversation should get practical and specific — ask about the specific behavior she is struggling with most.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Which of the four tools is most different from what you grew up with? Which feels most natural to you?</li><li>Think of a recurring behavior challenge with your child. Which tool might fit it best?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What is the behavior with your child that most activates your frustration right now?</li><li>When that behavior happens and you respond — what are you trying to achieve? What do you actually achieve?</li><li>What would the discipline-that-builds version of that response look like?</li><li>Have you ever been disciplined in a way that felt like it built you rather than broke you? What was that like?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 32);

-- Session 33 (Kids’ Bedroom · local #5) — "When children compete"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Kids’ Bedroom'), 33, 33, 'When children compete', 'Philippians 2:3–4', '<p>Sibling rivalry and the specific challenge of being the only referee as a single mother. Women explored how to know when to intervene and when to let children work it out. The specific dynamics of each child being uniquely known were discussed. This conversation should ask about her children specifically — not children in general.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Which of your children do you feel you know most uniquely right now? Is there one you feel less connected to?</li><li>What is your current approach when the fighting starts? What usually works, and what doesn’t?</li><li>As the only referee — what is the hardest part? What is one thing that would make it more manageable?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What is the dynamic between your children that concerns you most?</li><li>Is there a child who seems to carry a particular role in the family — the responsible one, the difficult one, the one who disappears? Where did that role come from?</li><li>What does each of your children need from you that is different from what the others need?</li><li>What do you wish someone had done differently when you were competing with a sibling — or feeling invisible in your family?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 33);

-- Session 34 (Kids’ Bedroom · local #6) — "The hard days"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Kids’ Bedroom'), 34, 34, 'The hard days', 'Proverbs 31:25', '<p>The closing Kids’ Bedroom session acknowledged the hard days honestly — compassion fatigue, the absent other parent, holding authority alone. The Blessing Card ceremony was done in group. This is often a session where women feel the weight of what they are carrying and also, sometimes, unexpected pride in what they have done. Ask both. The Blessing Card is worth discussing.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Where are you running on empty in your parenting right now? What is the most depleting thing?</li><li>What is the hardest specific challenge of parenting in your situation that other parents don’t have to navigate?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What is the thing about your parenting that you are most proud of — that no one sees or acknowledges?</li><li>What does the absence of the other parent cost your child? What does it cost you?</li><li>What does your child need from you on the hard days that you find hardest to give?</li><li>What is the blessing you want to speak over your child — the truth you want them to carry about themselves?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 34);

-- Session 35 (Office · local #1) — "You are God’s masterpiece"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Office'), 35, 35, 'You are God’s masterpiece', 'Ephesians 2:10', '<p>This session dismantled the lie that productivity and worth are linked. Women were asked to identify their gifts — including gifts forged through hard experience. The gifts inventory on the handout often produces surprises. Women frequently undervalue what comes naturally to them. This is a conversation to speak what you see in her — you may notice gifts she doesn’t.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What is one thing you do well that you have never thought of as a gift?</li><li>What has your hardest experience taught you that someone going through the same thing would need to hear?</li><li>If you could not fail — if fear and money and your past were not factors — what would you do?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What gift do you have that you consistently dismiss or minimize? Why do you do that?</li><li>Who in your life has named something in you — seen something you couldn’t see yourself?</li><li>What are you afraid of claiming — what is the dream or the calling that feels too big or too far away?</li><li>What would it mean to you to believe that God prepared specific good works for you in advance — not generic ones, but yours specifically?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 35);

-- Session 36 (Office · local #2) — "More than a job"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Office'), 36, 36, 'More than a job', 'Matthew 25:23', '<p>The parable of the talents was explored — not as pressure but as permission. Vocation vs. employment was named: what you are called to is bigger than any job title. Women began developing a vocation statement. The talent buried out of fear was identified. This is often a session where women begin to see themselves differently — as someone with a purpose that reaches beyond their current circumstances.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Have you ever done work — paid or unpaid — that felt like it mattered beyond the task itself?</li><li>What are the few things currently in your hands? What has God given you to work with right now?</li><li>What is the talent you are most tempted to bury out of fear? What is the fear?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What is your vocation statement from this session? Would you read it to me?</li><li>What does the life look like where you’re living that vocation — even partially?</li><li>What is the first small step toward that life that is available to you right now?</li><li>What would it mean to be faithful with what’s in your hands today, even if what’s in your hands feels small?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 36);

-- Session 37 (Office · local #3) — "Plans and a future"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Office'), 37, 37, 'Plans and a future', 'Jeremiah 29:11', '<p>The closing Office session applied the vision to a three-goal framework. Women identified one-year, three-year, and five-year goals — not wishes, but specific intentions. The Vision Board artifact was created. This session is about agency — not waiting for circumstances to be right, but beginning to build now. Ask about the specific goals she set.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Where have you been waiting for circumstances to improve before you start moving toward something?</li><li>Looking at your vocation statement from last week — what is one concrete step you can take in the next month?</li><li>What is the smallest possible first step you could take this week toward the future you described?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What are the three goals you set? Tell me about each one.</li><li>Which goal feels most reachable? Which feels most out of reach?</li><li>What is the fear or the lie that would most likely stop you from pursuing the one that feels out of reach?</li><li>What support would you need to actually move toward these goals? Who could help you?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 37);

-- Session 38 (Attic · local #1) — "Going through the boxes"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Attic'), 38, 38, 'Going through the boxes', 'Ecclesiastes 3:1', '<p>This session introduced the attic as the room of unfinished things — grief never fully grieved, relationships that ended without resolution, dreams packed away, old wounds stored rather than healed. Women categorized what’s in their attic. This is a gentle session to introduce but an important one — many women have been carrying things for years that they haven’t been given permission to set down.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What is one thing you know is in your attic — something unfinished, ungrieved, or packed away?</li><li>What has it cost you to leave that thing untended? How has it shown up in your life?</li><li>Is there one box that might be ready to be opened?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>How long have you been carrying that thing without looking at it?</li><li>What are you afraid you’ll find if you open that box?</li><li>Is there something in your attic that you have been waiting for permission to grieve? What would that permission feel like?</li><li>What is the one thing in your attic that, if you could set it down, would change how you walk through your daily life?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 38);

-- Session 39 (Attic · local #2) — "Permission to grieve"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Attic'), 39, 39, 'Permission to grieve', 'Lamentations 3:22–23', '<p>This session gave explicit permission to grieve — not as wallowing but as the appropriate response to real loss. Women wrote a private letter to what was lost. Grief as honest response rather than weakness was named. Many women in this program have had no space to grieve and have survived by not stopping. This conversation may be the first time she has been given real permission.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What is a loss you have never fully grieved? Something that was real and significant that you’ve had to just move through?</li><li>What did you learn about grief growing up? Was it welcomed, or were you expected to move on?</li><li>What would it mean to give this loss its proper place — to say: this mattered, and it deserved to be mourned?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What did you write in your letter to what was lost? Is there something from it you’d be willing to share?</li><li>What is the grief you have never had space to feel because you had to keep going?</li><li>What would it mean for God to grieve with you — not fix it, not explain it, but grieve with you?</li><li>Is there a specific loss that you sense God wants to sit with you in right now?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 39);

-- Session 40 (Attic · local #3) — "Letting go"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Attic'), 40, 40, 'Letting go', 'Isaiah 43:18–19', '<p>The distinction between acceptance and resignation was named carefully — letting go is not pretending something didn’t happen or didn’t matter. The bowl ceremony was done in group. This conversation should ask honestly: was the release real? Some things take more than one ceremony. Some things need to be grieved more before they can be released.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What is something you have been holding on to that you know you need to set down?</li><li>What is the difference between accepting something and pretending it didn’t matter?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>Was the release in group real for you, or are you still holding it?</li><li>What makes it hard to let go? Is it that letting go feels like saying it was okay?</li><li>Is there something you need to grieve more fully before you can release it? What would that look like?</li><li>What would your life look like if that thing no longer had a claim on you?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 40);

-- Session 41 (Attic · local #4) — "What outlasts you"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Attic'), 41, 41, 'What outlasts you', 'Proverbs 13:22', '<p>The closing Attic session turned toward legacy — not property but what you leave in people. The Legacy Card was written. This is often a session of significant meaning for women in transitional housing, who may feel they have nothing to leave. This is a conversation about the inheritance of character, faith, healing, and presence. The legacy card is worth reading together.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Looking at your house drawing from Session 1 alongside the house you are building now — what has changed?</li><li>What do you most want your children and grandchildren to inherit from you?</li><li>What is one thing from this year that you want to carry with you and one thing you want to leave behind?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What does your Legacy Card say? Would you read it to me?</li><li>What is the inheritance you are most afraid you won’t be able to give?</li><li>What is already in you — character, faith, love — that will outlast you whether you have money or not?</li><li>Who is watching you right now who will carry something of who you are?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 41);

-- Session 42 (Fence · local #1) — "Guard your heart"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Fence'), 42, 42, 'Guard your heart', 'Proverbs 4:23', '<p>This session explored the fence as a discernment tool for what we allow in from the outside world — media, content, and influences that shape us whether we notice or not. An inputs test was used. This is often a practical conversation — what is she actually taking in, and what is it producing in her?</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What are the primary things you are currently taking in regularly — media, conversations, content?</li><li>Using the inputs test from the session: what in your current diet is feeding you, and what is depleting you?</li><li>What is one deliberate input you want to add, and one you want to remove?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What are you taking in that you know is shaping you in a direction you don’t want to go?</li><li>What would it cost you to stop taking it in? What is the pull of it?</li><li>What is the one thing you could add to your life regularly that would most change what you produce?</li><li>What does it mean to you to actively choose what goes in — rather than just absorbing whatever comes?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 42);

-- Session 43 (Fence · local #2) — "Who you run with"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Fence'), 43, 43, 'Who you run with', '1 Corinthians 15:33', '<p>This session addressed community — the gravitational pull of the people we spend time with. Women did a community audit. The concept of an exit relationship — one that helps us exit from who we are becoming — was named. This conversation should get specific about the actual people in her life.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Who are the people you spend the most time with? What direction do they pull you?</li><li>Is there a relationship in your life that functions as an exit ramp — that pulls you back toward who you were rather than who you are becoming?</li><li>Who in your life sharpens you — who makes you more like the person you want to be?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>Name the specific relationships that are most pulling you backward right now. What is it about each one?</li><li>What would it actually take to spend less time in those relationships? What is the obstacle?</li><li>Who is one person you would like more of in your life — someone who pulls you forward?</li><li>What does healthy community look like for you specifically, given your life right now?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 43);

-- Session 44 (Tree in the Yard · local #1) — "Roots and seasons"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Tree in the Yard'), 44, 44, 'Roots and seasons', 'Jeremiah 17:7–8', '<p>This session explored the wisdom of seasons — that not every season is a season of fruit, and that deep roots come from endurance through hard seasons rather than from easy circumstances. Women were asked what season they are in and what roots have grown this year. This is a reflective conversation at the near-end of the curriculum year.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What season do you think you are in right now — growth, harvest, dormancy, or storm?</li><li>What roots have you grown this year? What is now deeper in you than it was twelve months ago?</li><li>When the heat comes — as it will — what do you now have that you didn’t have before this year?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>Looking back at the year — what was the hardest season, and what did it grow in you that a comfortable season couldn’t have?</li><li>What does your root system actually look like right now — what are you connected to and drawing life from?</li><li>Is there an area of your life where you know you need to go deeper before you can go further?</li><li>What do you want the roots of your life to be — specifically, what do you want to be drawing from?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 44);

-- Session 45 (Tree in the Yard · local #2) — "Fruit and shade"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Tree in the Yard'), 45, 45, 'Fruit and shade', 'John 15:5', '<p>The final session of Phase 5 looked at the fruit that is already appearing in the participant’s life — visible, real, for others. The concept of being shade for others was introduced. The Tree drawing artifact was created. This is the second-to-last unit before Whole House. A good moment to begin naming what she is taking out of this year.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Where do you see the fruit of the Spirit already appearing in your life that wasn’t there a year ago?</li><li>Who is growing in your shade — who benefits from what you have been built into this year?</li><li>What does it mean to you that the condition for fruit is abiding, not striving?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What is the most visible fruit in your life right now — the thing that is most different from where you started?</li><li>Who are you providing shade for, even if you don’t notice it?</li><li>What does abiding actually look like for you in a practical day — not the ideal version, but the real one?</li><li>As you get close to the end of this year — what do you want to carry forward, and what do you want to leave in the curriculum room?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 45);

-- Session 46 (Whole House · local #1) — "The inner work"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Whole House'), 46, 46, 'The inner work', '2 Corinthians 13:5', '<p>The Whole House unit is a walk-back through all six phases before graduation. Session 1 covered Phases 1 and 2 — Foundation, Basement, Front Door, Living Room, Kitchen, and Bathroom. Women held their Session 1 house drawing and wrote witness answers for each room. This is a session of honest stock-taking. Ask her what she sees that is genuinely different.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Holding your Session 1 house drawing — what do you notice?</li><li>What is your foundation made of now that you were not built on before this year?</li><li>What did you bring up from your basement that you are glad is no longer underground?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>Walk me through your house drawing from the beginning of the year. What word did you write in each room? And what would you write there now?</li><li>What is the most significant change in Phases 1 and 2 for you — the thing you can point to and say: that is different?</li><li>Is there a room from the first half of the year where you feel like you only scratched the surface? What would you want to go back to?</li><li>What do you want to say to the version of you who drew that first house?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 46);

-- Session 47 (Whole House · local #2) — "The personal and the purposeful"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Whole House'), 47, 47, 'The personal and the purposeful', 'Jeremiah 29:11', '<p>Session 2 of Whole House covered Phases 3 and 4 — the Master Bedroom, Kids’ Bedroom, Office, and Attic. Women brought their Letter to My Child, Blessing Card, vision statement, and legacy card. Artifact moments were woven throughout. This session is about the bravest and most personal work of the year. Ask what she is carrying from these units.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What is different in how you carry your history — your body, your rest, your healing — after the Master Bedroom unit?</li><li>What are you giving your children now that you were not giving them before this year?</li><li>What gift did you name in the Office that you had not claimed before?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What did you release from your attic this year? Does it feel released, or does it still have a pull?</li><li>Of everything in Phases 3 and 4 — the healing, the parenting, the purpose, the letting go — what cost you the most?</li><li>What do you want your children to know about what you did this year, and why?</li><li>What is the next brave thing after this program — the thing Phase 3 and 4 prepared you for?</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 47);

-- Session 48 (Whole House · local #3) — "The whole house"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Whole House'), 48, 48, 'The whole house', 'Proverbs 13:22', '<p>The final session before graduation. Phase 5 rooms were walked through, then women drew their final house drawing and placed it alongside the Session 1 drawing. The commissioning happened — the facilitator spoke one true thing over each woman, and the group offered a word. Legacy cards were read aloud. This is the most important mentoring conversation of the year. Come prepared. Speak what is true about her.</p>', '<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Who were you when you drew the house in Session 1? And who are you now?</li><li>What is different about what you allow in — and who you surround yourself with — after this year?</li><li>Where do you see fruit in your life that was not there a year ago?</li></ol>', '<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>Put both house drawings in front of you. Look at them together. What do you see?</li><li>What is the one true thing I want to speak over you before graduation — what I have seen in you this year?</li><li>What are you most afraid of as this program ends? What do you lose when the structure ends?</li><li>What is the first thing you want to do differently — starting the week after graduation?</li><li>What do you want your legacy to be? Read it to me. Let me hear it.</li></ul>'
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 48);

