-- Sparrow — LCP: the 4 sessions from 0086 that never actually landed (16, 22, 25, 45 —
-- each threw a syntax error on Byron's manual session-by-session run of 0086 on
-- 2026-08-01, on a different single word each time). Direct DB check confirms none of
-- the 4 committed anything (INSERTs are all-or-nothing), so this is a clean re-insert,
-- not a repair. Content is byte-for-byte identical to 0086's version of these 4
-- sessions — the only change is dollar-quoting every HTML field (per 0117's precedent)
-- so this can be run as a standalone file without any single-quote/apostrophe risk.
-- Each INSERT is independently idempotent (WHERE NOT EXISTS), safe to re-run.

-- Session 16 (Living Room · local #6) — "Making wise decisions and building toward what is good"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Living Room'), 16, 16, 'Making wise decisions and building toward what is good', 'Ruth 1:16',
  $s16mb$<p>This closing Living Room session gave women four questions for evaluating relationships and making wise decisions. Forgiveness was named as releasing a debt — not reconciliation or trust. Green flags were explored alongside red ones. The Coat of Arms artifact was created. This is often a session where women have made or are about to make a significant decision about a relationship. Ask what she is building toward.</p>$s16mb$,
  $s16he$<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What is one relationship you feel clearer about after this unit?</li><li>What does forgiveness actually mean for you — and is there someone you’re working on forgiving?</li><li>What is one green flag you are looking for in the relationships you let close?</li></ol>$s16he$,
  $s16gd$<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>Is there a relationship decision in front of you right now? What are the four questions telling you?</li><li>What does forgiveness feel like in your body when you’re working toward it — what is the actual experience?</li><li>Who are you building toward? What does the living room you want look like — who is in it, what does it feel like?</li><li>What is one thing from this unit that you want to carry into how you live from here?</li></ul>$s16gd$
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 16);

-- Session 22 (Bathroom · local #2) — "The wash — confession and cleansing"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Bathroom'), 22, 22, 'The wash — confession and cleansing', 'confession and cleansing',
  $s22mb$<p>This session explored confession — not as punishment or performance, but as the actual mechanism of freedom. The difference between shame and repentance was named carefully. Many women have experienced religion as shame-adding rather than shame-removing. This conversation may surface significant experiences of religious harm or conditional grace. Approach gently and without defensiveness.</p>$s22mb$,
  $s22he$<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Has the Christianity you have encountered felt more like something that adds to your shame or removes it?</li><li>What is the difference between shame and repentance in your own experience?</li><li>Is there something you have carried that you believed was beyond forgiveness?</li></ol>$s22he$,
  $s22gd$<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What does confession feel like in your body — is it relief, or is it dread?</li><li>What is the thing you most need to bring into the light right now? You don’t have to say it, but is it there?</li><li>Have you ever experienced genuine absolution — the sense that something was actually washed, not just managed?</li><li>What would it mean for that specific thing to be clean — genuinely, permanently clean?</li></ul>$s22gd$
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 22);

-- Session 25 (Master Bedroom · local #2) — "The way it was meant to be"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Master Bedroom'), 25, 25, 'The way it was meant to be', 'Genesis 1:31',
  $s25mb$<p>This session covered God’s original design for sexuality — good, sacred, not shameful. Shame entered in Genesis 3; it was not the design. For many women in this program, their experience of sexuality has been shaped by violation, exploitation, or shame-based religion rather than by God’s original intent. This conversation may be one of the most significant of the year. Approach with great care and gentleness.</p>$s25mb$,
  $s25he$<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>What messages did you receive growing up about your body and sexuality?</li><li>What is your honest reaction to hearing that God designed sexuality as good — not shameful?</li><li>What would change for you if you genuinely believed your body is good — made with intention and worthy of care?</li></ol>$s25he$,
  $s25gd$<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What has your experience of sexuality actually been? You don’t have to go into detail, but: has it been something that has given you life, or taken it?</li><li>What do you believe God thinks about what has happened to you in this area — or what you have done?</li><li>What does it mean to you that the shame was not the design — that it was not supposed to be this way?</li><li>What would it mean to receive your body back — as something that is yours, that is good, that deserves care?</li></ul>$s25gd$
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 25);

-- Session 45 (Tree in the Yard · local #2) — "Fruit and shade"
INSERT INTO lcp_sessions (unit_id, session_number, sort_order, title, scripture, mentor_brief, mentor_handout_echo, mentor_going_deeper)
SELECT (SELECT id FROM lcp_units WHERE name = 'Tree in the Yard'), 45, 45, 'Fruit and shade', 'John 15:5',
  $s45mb$<p>The final session of Phase 5 looked at the fruit that is already appearing in the participant’s life — visible, real, for others. The concept of being shade for others was introduced. The Tree drawing artifact was created. This is the second-to-last unit before Whole House. A good moment to begin naming what she is taking out of this year.</p>$s45mb$,
  $s45he$<p>These are the questions the participant worked through in group. Use them as natural conversation starters — she has already thought about them. Ask which one stayed with her most.</p><ol><li>Where do you see the fruit of the Spirit already appearing in your life that wasn’t there a year ago?</li><li>Who is growing in your shade — who benefits from what you have been built into this year?</li><li>What does it mean to you that the condition for fruit is abiding, not striving?</li></ol>$s45he$,
  $s45gd$<p>If the participant is open and ready, these questions go further than the group context typically allows. Use your judgment — not every conversation needs to go here. But when she is ready, these are the doors.</p><ul><li>What is the most visible fruit in your life right now — the thing that is most different from where you started?</li><li>Who are you providing shade for, even if you don’t notice it?</li><li>What does abiding actually look like for you in a practical day — not the ideal version, but the real one?</li><li>As you get close to the end of this year — what do you want to carry forward, and what do you want to leave in the curriculum room?</li></ul>$s45gd$
WHERE NOT EXISTS (SELECT 1 FROM lcp_sessions WHERE session_number = 45);
